[tool.poetry]
name = "change-exit-node"
version = "0.1.0"
description = ""
authors = ["gillesxr <gillesxr@tutanota.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
